# Generated by Django 6.0.7 on 2026-08-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "summary",
                    models.CharField(
                        help_text="Short card description (~150 chars).", max_length=300
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Full description for the detail page."
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="projects/"),
                ),
                ("repo_url", models.URLField(blank=True)),
                ("demo_url", models.URLField(blank=True)),
                (
                    "tags_csv",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags.", max_length=500
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "featured",
                    models.BooleanField(
                        default=False, help_text="Surface on the home page."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "-created_at"],
            },
        ),
    ]
